# Site
name: "Ismail Marmoush"
description: ""
meta_description: "Blog and Porfolio"
logo: 'assets/images/icons/favicon-32x32.png'
favicon: 'assets/images/icons/favicon.ico'
baseurl: /
google_analytics: 'UA-18732433-1'
disqus: 'ismailmarmoush'

# Authors
authors:
  ismailmarmoush:
    name: Ismail Marmoush
    display_name: Ismail Marmoush
    gravatar: "6a49fda271da86e318adb6ab42df344b"
    email: ismail@marmoush.com
    web: https://marmoush.com
    twitter: https://twitter.com/ismailmarmoush
    linkedin: https://www.linkedin.com/in/ismailmarmoush/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 100
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
